on:
  workflow_dispatch:

name: Deploy

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix develop -L --verbose

      - name: build-emscripten
        run: cd examples/playground &&  nix develop -c zig build -Dtarget=wasm32-emscripten -Doptimize=ReleaseSmall

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./zig-out/www/
          publish_branch: gh-pages
          destination_dir: .
